source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'appygram_ios_Example', :exclusive => true do
  pod "appygram_ios", :path => "../"
end

target 'appygram_ios_Tests', :exclusive => true do
  pod "appygram_ios", :path => "../"

  pod 'Quick'
  pod 'Nimble'
end
